version: '3.8'
services:
  stocks-pq-app-container:
    image: stocks-pq-app-img
    build: 
      context: "./"
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://stocks-pq-db-container:3306/stocksdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - stocks-pq-db-container
  stocks-pq-db-container:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: stocksdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
